sudo: required
services:
  - docker

before_install:
  - docker build -t bkempner/react-complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bkempner/react-complex-test yarn test -- --coverage

after_success:
  - docker build -t bkempner/react-complex-client ./client
  - docker build -t bkempner/react-complex-nginx ./nginx
  - docker build -t bkempner/react-complex-server ./server
  - docker build -t bkempner/react-complex-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push bkempner/react-complex-client
  - docker push bkempner/react-complex-nginx
  - docker push bkempner/react-complex-server
  - docker push bkempner/react-complex-worker
